name: Update Fast DXCC

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  id-token: write
  contents: write

jobs:
  update-fast-dxcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          check-latest: true
          registry-url: "https://registry.npmjs.org"
      - run: npm install -g pnpm npm@latest
      - run: pnpm install
      - name: Download and update CTY data
        working-directory: packages/fast-dxcc
        run: pnpm update-cty
      - name: Build package
        working-directory: packages/fast-dxcc
        run: pnpm build
      - name: Bump version and push changes
        working-directory: packages/fast-dxcc
        run: |
          # Check for changes
          if git diff --quiet src/data; then
            echo "No changes to commit"
            exit 0
          else
            echo "Changes to commit"
            
            # Configure Git
            git config --global user.name github-actions
            git config --global user.email github-actions@github.com
            
            # Bump version
            npm version minor
            
            # Commit and push changes
            git add src/data
            git add package.json
            git commit -m "chore: Update fast-dxcc"
            git push
          fi
      - name: Publish to NPM
        working-directory: packages/fast-dxcc
        run: npx publish-if-not-exists
